name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cuando hay cambios en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Asegúrate de que esta versión sea compatible con tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build  # Cambia esto si usas otro comando de construcción

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Cambia a la carpeta donde se genera tu sitio
