name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se despliega cuando hay cambios en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install # Usa este comando si tienes un proyecto Node.js con dependencias

      - name: Build the site
        run: npm run build # O el comando que utilices para construir tu sitio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Cambia a la carpeta donde están tus archivos estáticos (como 'dist' o 'build')
